version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "80:80"
  db:
    image: postgres:13
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
  monitoring:
    build:
      context: ./monitoring
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
      - "3000:3000"
