version: '3.8'

services:
  app:
    build: ./app
    container_name: honeypot_flask
    ports:
      - "5000:5000"  # Flask server
      - "8000:8000"  # Prometheus metrics
    depends_on:
      - db
    environment:
      - FLASK_ENV=development
    networks:
      - honeypot_network

  nginx:
    build: ./nginx
    container_name: honeypot_nginx
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - honeypot_network

  db:
    image: postgres:latest
    container_name: honeypot_db
    environment:
      POSTGRES_DB: honeypot
      POSTGRES_USER: honeypot_user
      POSTGRES_PASSWORD: password
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - honeypot_network

  prometheus:
    image: prom/prometheus:latest
    container_name: honeypot_prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - honeypot_network

  grafana:
    image: grafana/grafana:latest
    container_name: honeypot_grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - honeypot_network

networks:
  honeypot_network:
    driver: bridge
